### ISSUE TITLE
Error while running main.py

### ISSUE THREAD

**Issue by walterhunk** [jaloo555/flowbot#1]
Hi I am trying to get this going and I do have a premium flow-algo account. How do I get started in using this bot?

```
C:\Users\rahul\Downloads\flowbot-master\main.py:87: DeprecationWarning: use setter for headless property instead of set_headless
  chrome_opts.set_headless(headless=hideChrome)
Traceback (most recent call last):
  File "C:\Users\rahul\Downloads\flowbot-master\main.py", line 337, in <module>
    main()
  File "C:\Users\rahul\Downloads\flowbot-master\main.py", line 325, in main
    chromeSetup()
  File "C:\Users\rahul\Downloads\flowbot-master\main.py", line 98, in chromeSetup
    driver = webdriver.Chrome(executable_path=os.environ.get("CHROMEDRIVER_PATH"),options=chrome_opts)
  File "C:\Users\rahul\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\rahul\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1356, in _execute_child
    args = list2cmdline(args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 561, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\os.py", line 822, in fsdecode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by c0d3high** [comment]
hello,
I am having similar issues. Can you explain how to fully setup the bot? I input my username and password and channel ID in the main.py file
